"""Backend-neutral construction-drawing request helpers."""

from shellforgepy.drawing.construction import (
    CONSTRUCTION_DRAWING_BACKEND_SUPPORT,
    DEFAULT_SECTION_VIEW,
    SUPPORTED_VIEW_PRESETS,
    SVG_NS,
    ConstructionDrawingRequest,
    ConstructionDrawingView,
    DrawingBounds,
    ModelBounds,
    PartSelector,
    SectionViewFrame,
    Vector3,
    ViewPreset,
    append_arc,
    append_circle,
    append_line,
    append_part_group,
    create_svg_document,
    drawing_bounds_from_model_bounds,
    make_construction_drawing_request,
    model_point_to_drawing,
    render_construction_drawing,
    render_construction_drawing_parts,
    resolve_view_frame,
    serialize_svg,
)

__all__ = [
    "CONSTRUCTION_DRAWING_BACKEND_SUPPORT",
    "DEFAULT_SECTION_VIEW",
    "DrawingBounds",
    "ModelBounds",
    "SVG_NS",
    "ConstructionDrawingRequest",
    "ConstructionDrawingView",
    "PartSelector",
    "SectionViewFrame",
    "SUPPORTED_VIEW_PRESETS",
    "ViewPreset",
    "Vector3",
    "append_arc",
    "append_circle",
    "append_line",
    "append_part_group",
    "create_svg_document",
    "drawing_bounds_from_model_bounds",
    "make_construction_drawing_request",
    "model_point_to_drawing",
    "render_construction_drawing",
    "render_construction_drawing_parts",
    "resolve_view_frame",
    "serialize_svg",
]
