#!/bin/bash
# This script was generated by newshscript.sh

set -euo pipefail
trap 'echo "Script $0 failed at line $LINENO" >&2' ERR

SOURCE="${BASH_SOURCE[0]}"
while [ -h "${SOURCE}" ]; do
    DIR="$(cd -P "$(dirname "${SOURCE}")" &> /dev/null && pwd)"
    SOURCE="$(readlink "${SOURCE}")"
    [[ "${SOURCE}" != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
SCRIPT_DIR="$(cd -P "$(dirname "${SOURCE}")" &> /dev/null && pwd)"
SCRIPT_FULLPATH="$(realpath "${SOURCE}")"
PYTHON_SCRIPT="${SCRIPT_DIR}/new_part_file.py"
PYTHON_CMD="${PYTHON_CMD:-python3}"

echo "Running ${SCRIPT_FULLPATH} with args: $@"

if [ ! -f "${PYTHON_SCRIPT}" ]; then
    echo "Unable to find ${PYTHON_SCRIPT}" >&2
    exit 1
fi

exec "${PYTHON_CMD}" "${PYTHON_SCRIPT}" "$@"
